#!/usr/bin/env ruby
require_relative 'colorize'

message_file = ARGV[0]
message = File.read(message_file)

# regex to validate in commit msg
$commit_regex = /^(Merging|Merge) branch \'.*\' into feature\/|Merge remote-tracking branch |(\[[A-Z][A-Z][A-Z]+-\d{3,4}\])/

$error_msg="Aborting commit. Your commit message does not match the required pattern '[JIRA-NNNN] Your Message'!".red

file=`cat $1` # The file that contains the commit message

if !$commit_regex.match(message)
    puts $error_msg
    exit 1
end
