#!/bin/bash

#Small delegating script to allow multiple hooks in a git repository.
#Usage:
#Make your building system to create a symbolic link in the git hooks directory
#to this script with the name of the hook you want to attend. For example,
#``pre-commit``.

#For example:
#```
#.git/hooks/
#|_ pre-commit
#|_ pre-commit.d/
#   |_ 01-cpp_coding_standard
#   |_ 02-python_coding_standard
#   |_ 03-something_else
#```
#


ruby ~/.githooks/pre-commit.d/01-pre-commit-code
bash ~/.githooks/pre-commit.d/02-pre-commit-flux
