#!/bin/bash

#
# A hook script to verify that a push is not done with untracked source file
#
# To use it, either symlink this script to $your-git-clone/.git/hooks/pre-push
# or include it in your existing pre-push script.
#
 
RED=$(tput setaf 1)
NORMAL=$(tput sgr0)

# Perl-style regular expression which limits the files we interpret as source files.
# The default pattern here excludes CMakeLists.txt files and any .h/.cpp/.cmake files.
# Extend/adapt this to your needs. Alternatively, set the pattern in your repo via:
#     git config hooks.prepush.sourcepattern "$your-pattern"
pattern=$(git config --get hooks.prepush.sourcepattern)
if [ -z "$pattern" ]; then
  pattern="(?:(?:^|/)|\.java|\.yml|\.properties|)$"
fi
 
files=$(git status -u --porcelain --no-column | sed "s/^?? //")
if [ -z "$files" ]; then
	if [ -f "build.gradle" ]
	then
		./gradlew clean test --refresh-dependencies
		if [ $? -ne 0 ]; then
			echo "$RED Error while testing the code $NORMAL"
			exit 1
		fi
	elif [ -f "pom.xml" ]
	then
		mvn clean verify -U
		if [ $? -ne 0 ]; then
			echo "$RED Error while testing the code $NORMAL"
			exit 1
		fi
	else 
		echo "$RED Current folder contains neither build.gradle nor pom.xml, skipping tests $NORMAL"
	fi	
	exit 0
fi
 
echo
echo "$RED ERROR: Preventing push with untracked source files:"
echo
echo "$files" | sed "s/^/    /"
echo
echo "Either include these files in your commits, add them to .gitignore"
echo "or stash them with git stash -u."
echo "$NORMAL"
exit 1
